/** Generated by YAKINDU Statechart Tools code generator. */
package microwave.microwave;

import microwave.ITimer;

public class MicrowaveStatemachine implements IMicrowaveStatemachine {
	protected class SCInterfaceImpl implements SCInterface {
	
		private SCInterfaceOperationCallback operationCallback;
		
		public void setSCInterfaceOperationCallback(
				SCInterfaceOperationCallback operationCallback) {
			this.operationCallback = operationCallback;
		}
		private boolean high;
		
		
		public void raiseHigh() {
			high = true;
			runCycle();
		}
		
		private boolean low;
		
		
		public void raiseLow() {
			low = true;
			runCycle();
		}
		
		private boolean digit;
		
		private long digitValue;
		
		
		public void raiseDigit(final long value) {
			digitValue = value;
			digit = true;
			runCycle();
		}
		protected long getDigitValue() {
			if (! digit ) 
				throw new IllegalStateException("Illegal event value access. Event Digit is not raised!");
			return digitValue;
		}
		
		private boolean timer;
		
		
		public void raiseTimer() {
			timer = true;
			runCycle();
		}
		
		private boolean start;
		
		
		public void raiseStart() {
			start = true;
			runCycle();
		}
		
		private boolean stop;
		
		
		public void raiseStop() {
			stop = true;
			runCycle();
		}
		
		private boolean open;
		
		
		public void raiseOpen() {
			open = true;
			runCycle();
		}
		
		private boolean close;
		
		
		public void raiseClose() {
			close = true;
			runCycle();
		}
		
		private long power;
		
		public long getPower() {
			return power;
		}
		
		public void setPower(long value) {
			this.power = value;
		}
		
		protected void clearEvents() {
			high = false;
			low = false;
			digit = false;
			timer = false;
			start = false;
			stop = false;
			open = false;
			close = false;
		}
	}
	
	
	protected SCInterfaceImpl sCInterface;
	
	private boolean initialized = false;
	
	public enum State {
		microwave_Idle,
		microwave_SelectPower,
		microwave_SetTimer,
		microwave_Cooking,
		microwave_FinishedOn,
		microwave_FinishedOff,
		microwave_DoorOpen,
		microwave_WaitStart,
		$NullState$
	};
	
	private final State[] stateVector = new State[1];
	
	private int nextStateIndex;
	
	private ITimer timer;
	
	private final boolean[] timeEvents = new boolean[5];
	
	private long time;
	
	protected long getTime() {
		return time;
	}
	
	protected void setTime(long value) {
		this.time = value;
	}
	
	
	private long numDigits;
	
	protected long getNumDigits() {
		return numDigits;
	}
	
	protected void setNumDigits(long value) {
		this.numDigits = value;
	}
	
	
	private boolean wasCooking;
	
	protected boolean getWasCooking() {
		return wasCooking;
	}
	
	protected void setWasCooking(boolean value) {
		this.wasCooking = value;
	}
	
	
	private long fromState;
	
	protected long getFromState() {
		return fromState;
	}
	
	protected void setFromState(long value) {
		this.fromState = value;
	}
	
	
	private long blinkCount;
	
	protected long getBlinkCount() {
		return blinkCount;
	}
	
	protected void setBlinkCount(long value) {
		this.blinkCount = value;
	}
	
	
	public MicrowaveStatemachine() {
		sCInterface = new SCInterfaceImpl();
	}
	
	public void init() {
		this.initialized = true;
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		if (this.sCInterface.operationCallback == null) {
			throw new IllegalStateException("Operation callback for interface sCInterface must be set.");
		}
		
		for (int i = 0; i < 1; i++) {
			stateVector[i] = State.$NullState$;
		}
		clearEvents();
		clearOutEvents();
		sCInterface.setPower(0);
		
		setTime(0);
		
		setNumDigits(0);
		
		setWasCooking(false);
		
		setFromState(0);
		
		setBlinkCount(0);
	}
	
	public void enter() {
		if (!initialized) {
			throw new IllegalStateException(
				"The state machine needs to be initialized first by calling the init() function."
			);
		}
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		enterSequence_Microwave_default();
	}
	
	public void runCycle() {
		if (!initialized)
			throw new IllegalStateException(
					"The state machine needs to be initialized first by calling the init() function.");
		clearOutEvents();
		for (nextStateIndex = 0; nextStateIndex < stateVector.length; nextStateIndex++) {
			switch (stateVector[nextStateIndex]) {
			case microwave_Idle:
				microwave_Idle_react(true);
				break;
			case microwave_SelectPower:
				microwave_SelectPower_react(true);
				break;
			case microwave_SetTimer:
				microwave_SetTimer_react(true);
				break;
			case microwave_Cooking:
				microwave_Cooking_react(true);
				break;
			case microwave_FinishedOn:
				microwave_FinishedOn_react(true);
				break;
			case microwave_FinishedOff:
				microwave_FinishedOff_react(true);
				break;
			case microwave_DoorOpen:
				microwave_DoorOpen_react(true);
				break;
			case microwave_WaitStart:
				microwave_WaitStart_react(true);
				break;
			default:
				// $NullState$
			}
		}
		clearEvents();
	}
	public void exit() {
		exitSequence_Microwave();
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public boolean isActive() {
		return stateVector[0] != State.$NullState$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public boolean isFinal() {
		return false;
	}
	/**
	* This method resets the incoming events (time events included).
	*/
	protected void clearEvents() {
		sCInterface.clearEvents();
		for (int i=0; i<timeEvents.length; i++) {
			timeEvents[i] = false;
		}
	}
	
	/**
	* This method resets the outgoing events.
	*/
	protected void clearOutEvents() {
	}
	
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public boolean isStateActive(State state) {
	
		switch (state) {
		case microwave_Idle:
			return stateVector[0] == State.microwave_Idle;
		case microwave_SelectPower:
			return stateVector[0] == State.microwave_SelectPower;
		case microwave_SetTimer:
			return stateVector[0] == State.microwave_SetTimer;
		case microwave_Cooking:
			return stateVector[0] == State.microwave_Cooking;
		case microwave_FinishedOn:
			return stateVector[0] == State.microwave_FinishedOn;
		case microwave_FinishedOff:
			return stateVector[0] == State.microwave_FinishedOff;
		case microwave_DoorOpen:
			return stateVector[0] == State.microwave_DoorOpen;
		case microwave_WaitStart:
			return stateVector[0] == State.microwave_WaitStart;
		default:
			return false;
		}
	}
	
	/**
	* Set the {@link ITimer} for the state machine. It must be set
	* externally on a timed state machine before a run cycle can be correctly
	* executed.
	* 
	* @param timer
	*/
	public void setTimer(ITimer timer) {
		this.timer = timer;
	}
	
	/**
	* Returns the currently used timer.
	* 
	* @return {@link ITimer}
	*/
	public ITimer getTimer() {
		return timer;
	}
	
	public void timeElapsed(int eventID) {
		timeEvents[eventID] = true;
		runCycle();
	}
	
	public SCInterface getSCInterface() {
		return sCInterface;
	}
	
	public void raiseHigh() {
		sCInterface.raiseHigh();
	}
	
	public void raiseLow() {
		sCInterface.raiseLow();
	}
	
	public void raiseDigit(long value) {
		sCInterface.raiseDigit(value);
	}
	
	public void raiseTimer() {
		sCInterface.raiseTimer();
	}
	
	public void raiseStart() {
		sCInterface.raiseStart();
	}
	
	public void raiseStop() {
		sCInterface.raiseStop();
	}
	
	public void raiseOpen() {
		sCInterface.raiseOpen();
	}
	
	public void raiseClose() {
		sCInterface.raiseClose();
	}
	
	public long getPower() {
		return sCInterface.getPower();
	}
	
	public void setPower(long value) {
		sCInterface.setPower(value);
	}
	
	/* Entry action for state 'Idle'. */
	private void entryAction_Microwave_Idle() {
		sCInterface.operationCallback.clearDisplay();
		
		sCInterface.operationCallback.closeDoor();
		
		setTime(0);
		
		setNumDigits(0);
		
		setWasCooking(false);
		
		sCInterface.setPower(0);
		
		setFromState(0);
		
		setBlinkCount(0);
	}
	
	/* Entry action for state 'Cooking'. */
	private void entryAction_Microwave_Cooking() {
		timer.setTimer(this, 0, (1 * 1000), false);
		
		timer.setTimer(this, 1, (1 * 1000), false);
	}
	
	/* Entry action for state 'FinishedOn'. */
	private void entryAction_Microwave_FinishedOn() {
		timer.setTimer(this, 2, 500, false);
		
		sCInterface.operationCallback.beepOn();
		
		sCInterface.operationCallback.display("Finished");
	}
	
	/* Entry action for state 'FinishedOff'. */
	private void entryAction_Microwave_FinishedOff() {
		timer.setTimer(this, 3, 500, false);
		
		timer.setTimer(this, 4, 500, false);
		
		sCInterface.operationCallback.beepOff();
		
		sCInterface.operationCallback.clearDisplay();
	}
	
	/* Entry action for state 'DoorOpen'. */
	private void entryAction_Microwave_DoorOpen() {
		sCInterface.operationCallback.openDoor();
		
		sCInterface.operationCallback.display("Waiting");
	}
	
	/* Entry action for state 'WaitStart'. */
	private void entryAction_Microwave_WaitStart() {
		sCInterface.operationCallback.closeDoor();
		
		sCInterface.operationCallback.displayTime(getTime());
	}
	
	/* Exit action for state 'Cooking'. */
	private void exitAction_Microwave_Cooking() {
		timer.unsetTimer(this, 0);
		
		timer.unsetTimer(this, 1);
	}
	
	/* Exit action for state 'FinishedOn'. */
	private void exitAction_Microwave_FinishedOn() {
		timer.unsetTimer(this, 2);
	}
	
	/* Exit action for state 'FinishedOff'. */
	private void exitAction_Microwave_FinishedOff() {
		timer.unsetTimer(this, 3);
		
		timer.unsetTimer(this, 4);
	}
	
	/* 'default' enter sequence for state Idle */
	private void enterSequence_Microwave_Idle_default() {
		entryAction_Microwave_Idle();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_Idle;
	}
	
	/* 'default' enter sequence for state SelectPower */
	private void enterSequence_Microwave_SelectPower_default() {
		nextStateIndex = 0;
		stateVector[0] = State.microwave_SelectPower;
	}
	
	/* 'default' enter sequence for state SetTimer */
	private void enterSequence_Microwave_SetTimer_default() {
		nextStateIndex = 0;
		stateVector[0] = State.microwave_SetTimer;
	}
	
	/* 'default' enter sequence for state Cooking */
	private void enterSequence_Microwave_Cooking_default() {
		entryAction_Microwave_Cooking();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_Cooking;
	}
	
	/* 'default' enter sequence for state FinishedOn */
	private void enterSequence_Microwave_FinishedOn_default() {
		entryAction_Microwave_FinishedOn();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_FinishedOn;
	}
	
	/* 'default' enter sequence for state FinishedOff */
	private void enterSequence_Microwave_FinishedOff_default() {
		entryAction_Microwave_FinishedOff();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_FinishedOff;
	}
	
	/* 'default' enter sequence for state DoorOpen */
	private void enterSequence_Microwave_DoorOpen_default() {
		entryAction_Microwave_DoorOpen();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_DoorOpen;
	}
	
	/* 'default' enter sequence for state WaitStart */
	private void enterSequence_Microwave_WaitStart_default() {
		entryAction_Microwave_WaitStart();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_WaitStart;
	}
	
	/* 'default' enter sequence for region Microwave */
	private void enterSequence_Microwave_default() {
		react_Microwave__entry_Default();
	}
	
	/* Default exit sequence for state Idle */
	private void exitSequence_Microwave_Idle() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state SelectPower */
	private void exitSequence_Microwave_SelectPower() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state SetTimer */
	private void exitSequence_Microwave_SetTimer() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Cooking */
	private void exitSequence_Microwave_Cooking() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_Microwave_Cooking();
	}
	
	/* Default exit sequence for state FinishedOn */
	private void exitSequence_Microwave_FinishedOn() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_Microwave_FinishedOn();
	}
	
	/* Default exit sequence for state FinishedOff */
	private void exitSequence_Microwave_FinishedOff() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_Microwave_FinishedOff();
	}
	
	/* Default exit sequence for state DoorOpen */
	private void exitSequence_Microwave_DoorOpen() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state WaitStart */
	private void exitSequence_Microwave_WaitStart() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for region Microwave */
	private void exitSequence_Microwave() {
		switch (stateVector[0]) {
		case microwave_Idle:
			exitSequence_Microwave_Idle();
			break;
		case microwave_SelectPower:
			exitSequence_Microwave_SelectPower();
			break;
		case microwave_SetTimer:
			exitSequence_Microwave_SetTimer();
			break;
		case microwave_Cooking:
			exitSequence_Microwave_Cooking();
			break;
		case microwave_FinishedOn:
			exitSequence_Microwave_FinishedOn();
			break;
		case microwave_FinishedOff:
			exitSequence_Microwave_FinishedOff();
			break;
		case microwave_DoorOpen:
			exitSequence_Microwave_DoorOpen();
			break;
		case microwave_WaitStart:
			exitSequence_Microwave_WaitStart();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_Microwave__entry_Default() {
		enterSequence_Microwave_Idle_default();
	}
	
	private boolean react() {
		return false;
	}
	
	private boolean microwave_Idle_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (sCInterface.high) {
					exitSequence_Microwave_Idle();
					sCInterface.setPower(1);
					
					sCInterface.operationCallback.display("High");
					
					enterSequence_Microwave_SelectPower_default();
				} else {
					if (sCInterface.low) {
						exitSequence_Microwave_Idle();
						sCInterface.setPower(2);
						
						sCInterface.operationCallback.display("Low");
						
						enterSequence_Microwave_SelectPower_default();
					} else {
						if (sCInterface.open) {
							exitSequence_Microwave_Idle();
							setFromState(0);
							
							enterSequence_Microwave_DoorOpen_default();
						} else {
							did_transition = false;
						}
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_SelectPower_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (sCInterface.high) {
					exitSequence_Microwave_SelectPower();
					sCInterface.setPower(1);
					
					sCInterface.operationCallback.display("High");
					
					enterSequence_Microwave_SelectPower_default();
				} else {
					if (sCInterface.low) {
						exitSequence_Microwave_SelectPower();
						sCInterface.setPower(2);
						
						sCInterface.operationCallback.display("Low");
						
						enterSequence_Microwave_SelectPower_default();
					} else {
						if (sCInterface.timer) {
							exitSequence_Microwave_SelectPower();
							setTime(0);
							
							setNumDigits(0);
							
							sCInterface.operationCallback.clearDisplay();
							
							enterSequence_Microwave_SetTimer_default();
						} else {
							if (sCInterface.open) {
								exitSequence_Microwave_SelectPower();
								setFromState(1);
								
								enterSequence_Microwave_DoorOpen_default();
							} else {
								if (sCInterface.stop) {
									exitSequence_Microwave_SelectPower();
									enterSequence_Microwave_Idle_default();
								} else {
									did_transition = false;
								}
							}
						}
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_SetTimer_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (((sCInterface.digit) && (getNumDigits()<4))) {
					exitSequence_Microwave_SetTimer();
					setTime(((time * 10) + sCInterface.getDigitValue()));
					
					setNumDigits((numDigits + 1));
					
					sCInterface.operationCallback.displayTime(getTime());
					
					enterSequence_Microwave_SetTimer_default();
				} else {
					if (((sCInterface.start) && (getTime()>0))) {
						exitSequence_Microwave_SetTimer();
						sCInterface.operationCallback.cook();
						
						sCInterface.operationCallback.displayTime(getTime());
						
						enterSequence_Microwave_Cooking_default();
					} else {
						if (sCInterface.open) {
							exitSequence_Microwave_SetTimer();
							setFromState(2);
							
							enterSequence_Microwave_DoorOpen_default();
						} else {
							if (sCInterface.stop) {
								exitSequence_Microwave_SetTimer();
								enterSequence_Microwave_Idle_default();
							} else {
								did_transition = false;
							}
						}
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_Cooking_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (((timeEvents[0]) && (getTime()>1))) {
					exitSequence_Microwave_Cooking();
					setTime((time - 1));
					
					sCInterface.operationCallback.displayTime(getTime());
					
					enterSequence_Microwave_Cooking_default();
				} else {
					if (((timeEvents[1]) && (getTime()<=1))) {
						exitSequence_Microwave_Cooking();
						setTime(0);
						
						sCInterface.operationCallback.stopCook();
						
						setBlinkCount(0);
						
						enterSequence_Microwave_FinishedOn_default();
					} else {
						if (sCInterface.open) {
							exitSequence_Microwave_Cooking();
							sCInterface.operationCallback.stopCook();
							
							setWasCooking(true);
							
							setFromState(3);
							
							enterSequence_Microwave_DoorOpen_default();
						} else {
							if (sCInterface.stop) {
								exitSequence_Microwave_Cooking();
								sCInterface.operationCallback.stopCook();
								
								enterSequence_Microwave_Idle_default();
							} else {
								did_transition = false;
							}
						}
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_FinishedOn_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (timeEvents[2]) {
					exitSequence_Microwave_FinishedOn();
					enterSequence_Microwave_FinishedOff_default();
				} else {
					if (sCInterface.open) {
						exitSequence_Microwave_FinishedOn();
						sCInterface.operationCallback.beepOff();
						
						setFromState(4);
						
						setWasCooking(false);
						
						enterSequence_Microwave_DoorOpen_default();
					} else {
						if (sCInterface.stop) {
							exitSequence_Microwave_FinishedOn();
							sCInterface.operationCallback.beepOff();
							
							enterSequence_Microwave_Idle_default();
						} else {
							did_transition = false;
						}
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_FinishedOff_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (((timeEvents[3]) && (getBlinkCount()<4))) {
					exitSequence_Microwave_FinishedOff();
					setBlinkCount((blinkCount + 1));
					
					enterSequence_Microwave_FinishedOn_default();
				} else {
					if (((timeEvents[4]) && (getBlinkCount()>=4))) {
						exitSequence_Microwave_FinishedOff();
						enterSequence_Microwave_Idle_default();
					} else {
						if (sCInterface.open) {
							exitSequence_Microwave_FinishedOff();
							setFromState(5);
							
							setWasCooking(false);
							
							enterSequence_Microwave_DoorOpen_default();
						} else {
							if (sCInterface.stop) {
								exitSequence_Microwave_FinishedOff();
								enterSequence_Microwave_Idle_default();
							} else {
								did_transition = false;
							}
						}
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_DoorOpen_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (((sCInterface.close) && (getWasCooking()))) {
					exitSequence_Microwave_DoorOpen();
					sCInterface.operationCallback.closeDoor();
					
					sCInterface.operationCallback.displayTime(getTime());
					
					enterSequence_Microwave_WaitStart_default();
				} else {
					if (((sCInterface.close) && (((!getWasCooking() && getFromState()==1) && sCInterface.getPower()==1)))) {
						exitSequence_Microwave_DoorOpen();
						sCInterface.operationCallback.closeDoor();
						
						sCInterface.operationCallback.display("High");
						
						enterSequence_Microwave_SelectPower_default();
					} else {
						if (((sCInterface.close) && (((!getWasCooking() && getFromState()==1) && sCInterface.getPower()==2)))) {
							exitSequence_Microwave_DoorOpen();
							sCInterface.operationCallback.closeDoor();
							
							sCInterface.operationCallback.display("Low");
							
							enterSequence_Microwave_SelectPower_default();
						} else {
							if (((sCInterface.close) && ((!getWasCooking() && getFromState()==2)))) {
								exitSequence_Microwave_DoorOpen();
								sCInterface.operationCallback.closeDoor();
								
								sCInterface.operationCallback.displayTime(getTime());
								
								enterSequence_Microwave_SetTimer_default();
							} else {
								if (((sCInterface.close) && ((!getWasCooking() && getFromState()==4)))) {
									exitSequence_Microwave_DoorOpen();
									sCInterface.operationCallback.closeDoor();
									
									enterSequence_Microwave_FinishedOn_default();
								} else {
									if (((sCInterface.close) && ((!getWasCooking() && getFromState()==5)))) {
										exitSequence_Microwave_DoorOpen();
										sCInterface.operationCallback.closeDoor();
										
										enterSequence_Microwave_FinishedOff_default();
									} else {
										if (((sCInterface.close) && ((!getWasCooking() && getFromState()==0)))) {
											exitSequence_Microwave_DoorOpen();
											sCInterface.operationCallback.closeDoor();
											
											enterSequence_Microwave_Idle_default();
										} else {
											if (sCInterface.stop) {
												exitSequence_Microwave_DoorOpen();
												sCInterface.operationCallback.closeDoor();
												
												enterSequence_Microwave_Idle_default();
											} else {
												did_transition = false;
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_WaitStart_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (sCInterface.start) {
					exitSequence_Microwave_WaitStart();
					sCInterface.operationCallback.cook();
					
					sCInterface.operationCallback.displayTime(getTime());
					
					enterSequence_Microwave_Cooking_default();
				} else {
					if (sCInterface.open) {
						exitSequence_Microwave_WaitStart();
						setWasCooking(true);
						
						setFromState(3);
						
						enterSequence_Microwave_DoorOpen_default();
					} else {
						if (sCInterface.stop) {
							exitSequence_Microwave_WaitStart();
							enterSequence_Microwave_Idle_default();
						} else {
							did_transition = false;
						}
					}
				}
			}
		}
		return did_transition;
	}
	
}
